language: php
php:
  - 5.6

before_script:
  - composer install --no-interaction

script: phpunit --configuration phpunit.xml --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v