language: php
php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install --no-interaction

script: phpunit --configuration test/phpunit.xml --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v