language: php
php:
  - 5.6
  - hhvm

before_script:
  - composer install

script: phpunit --configuration test/phpunit.xml --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v